print("Please enter the following information:")
fn = input("First name: ")
ln = input("Last name: ")
em = input("Email address: ")
ph = input("Phone number: ")
job = input("Job title: ")
idd = input("ID Number: ")
ch = input("Hair Color: ")
cy = input("Eye Color: ")
month = input(" Started Month: ")
training = input("Training completed?")

print("The ID Card is: ")
print("---------------------------------------")
print(f"{ln.upper()}, {fn.capitalize()}")
print(job)
print("ID: ", idd)
print()
print(em.lower())
print(ph)
print()
print(f"Hair:  {ch:16} Eyes:{cy}")
print(f"Month: {month:12} Training:{training}")
print("---------------------------------------")
